"""Writes FINAL_REPORT.md from the result files (called by scripts/review3.py; can be run on its own)."""
from __future__ import annotations

import json
import os
import sys
from datetime import date


def _load(path):
    return json.load(open(path)) if os.path.exists(path) else None


def _row(rows, key):
    return next((r for r in rows if r["key"] == key), None)


def _pct(x, d=0):
    return "—" if x is None else f"{x * 100:.{d}f}%"


def write(root: str, tests_ok=None) -> str:
    res = os.path.join(root, "app", "services", "anomaly", "results")
    clf = _load(os.path.join(res, "fault_classifier_eval.json"))
    live = _load(os.path.join(res, "v2_live_eval.json"))
    fk = _load(os.path.join(res, "forklift_results.json"))
    sk = _load(os.path.join(res, "skab_results.json"))
    L = [f"# ARK Predict — final report (Review 3)", "",
         f"*Generated by `python scripts/review3.py` on {date.today().isoformat()}. Every number below is read "
         f"from the result files in `app/services/anomaly/results/`.*", ""]

    L += ["## What ARK Predict does", "",
          "Streaming, severity-aware anomaly detection for forklift sensors (HTH-ML-10). Every second, for every truck:",
          "", "1. **Detect** — load-aware statistical detectors (spike / drift / dropout / stuck) + unsupervised ML "
          "(Isolation Forest, joint-shift Gaussian, temporal autoencoder) decide *whether* something is wrong.",
          "2. **Diagnose (v2, new)** — a supervised fault classifier names *what* it is (8 fault types).",
          "3. **Score & route** — explainable 0–100 severity → IGNORE / MONITOR / URGENT, with alert-fatigue controls.",
          "4. **Learn** — technician verdicts tune severity and become new training labels for the classifier.", ""]

    if clf:
        L += ["## 1. The fault classifier (ARK Predict v2)", "",
              "Gradient boosting (scikit-learn `HistGradientBoostingClassifier`) on 57 features computed from the last "
              "60 s of each truck's residuals. Trained on labelled faults from simulator runs; **tested on runs it "
              "never saw** (different random seeds).", "",
              f"* **Right fault type for {_pct(clf['faultTypeAccuracy'])} of {clf['faultsTested']} unseen faults**",
              f"* Healthy seconds wrongly called a fault (raw, before the 10-of-15 s confirmation): "
              f"{_pct(clf['healthySecondsFlagged'], 1)}", "", "| Fault type | Faults | Named correctly |", "|---|---:|---:|"]
        for c, v in clf["perClass"].items():
            L.append(f"| {c.replace('_', ' ')} | {v['faults']} | {v['correct']} |")
        L.append("")

    if live:
        v1, v2 = live["v1"], live["v2"]
        L += ["## 2. v2 running live on the forklift stream", "",
              "Same simulated fleet (5 trucks, same injected faults), with and without the classifier:", "",
              "| | v1 (detectors + unsupervised ML) | **v2 (+ fault classifier)** |", "|---|---:|---:|",
              f"| Faults detected | {_pct(v1['detectionRate'])} | {_pct(v2['detectionRate'])} |",
              f"| Severity tier exactly right | {_pct(v1['exactTier'])} | {_pct(v2['exactTier'])} |",
              f"| URGENT faults paged | {_pct(v1['urgentRecall'])} | {_pct(v2['urgentRecall'])} |",
              f"| Median seconds until an URGENT page | {v1['medianSecondsToUrgent']:.0f} s | {v2['medianSecondsToUrgent']:.0f} s |",
              f"| False alarms per hour | {v1['falseAlarmsPerHour']} | {v2['falseAlarmsPerHour']} |",
              f"| Alerts sent | {v1['alertsSent']} | {v2['alertsSent']} |",
              f"| Alerted faults whose type is named correctly | — | **{_pct(v2['diagnosisAccuracy'])}** |", "",
              "The classifier never opens an incident on its own (so it cannot add false alarms). It names the fault on "
              "incidents the detectors opened, and lifts a confident *bearing wear* or *hydraulic leak* diagnosis to "
              "URGENT straight away.", ""]

    def bench(d, title, note):
        rows = d["rows"]
        fx, hy = _row(rows, "fixed"), _row(rows, "hybrid_past")
        out = [f"## {title}", "", note, "",
               "| Model | Setting | F1 | False-alarm rate | Faults caught | False-alarm episodes / h |",
               "|---|---|---:|---:|---:|---:|"]
        for r in rows:
            out.append(f"| {r['label']} | {r['mode']} | {r['f1']:.2f} | {r['far']:.1f}% | "
                       f"{r['faults_caught']}/{r['faults']} | {r['false_alarm_episodes_per_h']:.1f} |")
        if fx and hy:
            out += ["", f"**Headline:** fixed limit F1 {fx['f1']:.2f}, {fx['far']:.0f}% false-alarm rate, "
                        f"{fx['false_alarm_episodes_per_h']:.0f} false-alarm episodes/h → ARK Predict v2 F1 {hy['f1']:.2f}, "
                        f"{hy['far']:.0f}%, {hy['false_alarm_episodes_per_h']:.0f}/h, {hy['faults_caught']}/{hy['faults']} faults caught "
                        f"(supervised part trained only on earlier runs)."]
        return out + [""]

    if fk:
        L += bench(fk, "3. Forklift benchmark — fixed limit vs 10 models",
                   f"{fk['dataset']['files']} labelled forklift runs (`data/forklift/`, one injected fault each), "
                   "evaluated with the SKAB protocol: first 400 s train, the rest is test; settings tuned by grouped "
                   "cross-validation over the fault families sensor / wear / load.")
    if sk:
        L += bench(sk, "4. Real industrial data — SKAB benchmark",
                   "34 real water-pump experiments (Skoltech Anomaly Benchmark), official leaderboard protocol; "
                   "details in [SKAB_RESULTS.md](./SKAB_RESULTS.md).")

    L += ["## Reproduce", "", "```bash", "python scripts/review3.py            # everything",
          "python scripts/review3.py --quick    # faster, smaller runs", "python scripts/review3.py --skab     # + SKAB (needs SKAB/data)",
          "```", ""]
    if tests_ok is not None:
        L += [f"Tests: {'all passing' if tests_ok else 'SOME FAILING — see the console output'}.", ""]
    L += ["## Limits", "", "* Forklift numbers come from our simulator (labelled ground truth); SKAB is real but a pump, "
          "not a forklift. Real forklift data is the next step.",
          "* The classifier only knows the 8 fault types it was trained on; anything new is left to the unsupervised "
          "tier (MONITOR) until technicians label it and it is retrained.", ""]
    path = os.path.join(root, "FINAL_REPORT.md")
    open(path, "w").write("\n".join(L))
    return path


if __name__ == "__main__":
    print(write(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    sys.exit(0)
